# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cdad2674f2d959a9516d7fa6c2c1debc518c456b905a566a1d4cce90a2b6fe2edd1de7fb92039ccad7eaaf37286ea45066de6bee91d621f0bda709fde939da16

test:
  secret_key_base: 4a102a2bdfede15ef8e85be3c01ce87b5705cf8cfad2d73cac83778801871bcd6f7294f3bffe789131d0ba51f37d32fe0e398a49103da233478346b5fcea7e6e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
